import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "@/styles/Home.module.css";
import { Col, Container, Row } from "react-bootstrap";
import { BsLinkedin } from "react-icons/bs";
import { FaGithub, FaGlobe } from "react-icons/fa";
import { LuFileDown } from "react-icons/lu";

export default function Home() {
  return (
    <>
      <Head>
        <title>Nikhil Mishra</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <section>
        <Container className={styles.main}>
          <Row className={styles.cardContainer}>
            <Col className={styles.descripcion}>
              <h1>Nikhil Mishra</h1>
              <h2>Web Developer</h2>
              <p>{"Hi there! I'm Nikhil, an enthusiastic web developer with 1.2 years of experience in front-end and back-end development. I specialize in HTML, CSS, JavaScript, and frameworks like React and Angular. I'm passionate about creating clean, dynamic, and user-centric websites, always aiming to enhance user experience and optimize performance. Let’s build something amazing together!"}</p>
              <div className={styles.icons}>
                <Link href="https://www.linkedin.com/in/nikhil-mishra-664672180/" title="LinkedIn" target="_blank"><BsLinkedin /></Link>
                <Link href="https://www.github.com/nikhil7476/" title="GitHub" target="_blank"><FaGithub /></Link>
                <Link href="/Nikhil-Mishra-Resume.pdf" title="Resume" target="_blank"><LuFileDown /></Link>
                <Link href="#" title="Website" target="_self"><FaGlobe /></Link>
              </div>
            </Col>
            <Col className={styles.image}>
              <Image src="/nikhil-mishra.jpg" alt="Nikhil-Mishra" title="Nikhil Mishra" width={100} height={100} />
            </Col>
          </Row>
        </Container>
      </section>
    </>
  );
}
